### PR TITLE
Change image name

### PR DESCRIPTION
**Pull request by ShockwaveNN**
Seems old image name was called `finalduty/docker`, but seems now it `finalduty/archlinux`
And `docker pull finalduty/docker:daily` cause
`Error response from daemon: repository finalduty/docker not found: does not exist or no pull access`

### CODE REVIEW

**Comment by finalduty** [comment]
Well spotted, thanks. I noticed an extra line return added at Line 36 in your commit. If you're able to correct that I'll be happy to merge this PR.

**Comment by ShockwaveNN** [comment]
@finalduty Hi, sorry for long response. I'm working on it now. Repo download is pretty slow because of big archive size :)

**Comment by ShockwaveNN** [comment]
@finalduty Oh, something went wrong and github automatically closed this issue :( I will create new

**Comment by ShockwaveNN** [comment]
Fixed in #5

**Pull request closed without merging**
